// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UzayProjectAPI.Model;

#nullable disable

namespace UzayProjectAPI.Migrations
{
    [DbContext(typeof(ProjeContext))]
    [Migration("20231208194703_FirstDB")]
    partial class FirstDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("UzayProjectAPI.Models.Gezegenler", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GezegenAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("UzayID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("UzayID");

                    b.ToTable("Gezegenler");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            GezegenAdi = "Gezegen A",
                            UzayID = 1
                        },
                        new
                        {
                            ID = 2,
                            GezegenAdi = "Gezegen B",
                            UzayID = 1
                        },
                        new
                        {
                            ID = 3,
                            GezegenAdi = "Gezegen C",
                            UzayID = 2
                        },
                        new
                        {
                            ID = 4,
                            GezegenAdi = "Gezegen D",
                            UzayID = 2
                        },
                        new
                        {
                            ID = 5,
                            GezegenAdi = "Gezegen E",
                            UzayID = 3
                        });
                });

            modelBuilder.Entity("UzayProjectAPI.Models.Uydular", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Derece")
                        .HasColumnType("TEXT");

                    b.Property<int>("GezegenID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UyduAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("GezegenID");

                    b.ToTable("Uydular");
                });

            modelBuilder.Entity("UzayProjectAPI.Models.Uzaylar", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("UzayAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Uzaylar");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            UzayAdi = "Uzay A"
                        },
                        new
                        {
                            ID = 2,
                            UzayAdi = "Uzay B"
                        },
                        new
                        {
                            ID = 3,
                            UzayAdi = "Uzay C"
                        });
                });

            modelBuilder.Entity("UzayProjectAPI.Models.Gezegenler", b =>
                {
                    b.HasOne("UzayProjectAPI.Models.Uzaylar", "Uzaylar")
                        .WithMany("Gezegenler")
                        .HasForeignKey("UzayID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Uzaylar");
                });

            modelBuilder.Entity("UzayProjectAPI.Models.Uydular", b =>
                {
                    b.HasOne("UzayProjectAPI.Models.Gezegenler", "Gezegen")
                        .WithMany("Uydular")
                        .HasForeignKey("GezegenID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gezegen");
                });

            modelBuilder.Entity("UzayProjectAPI.Models.Gezegenler", b =>
                {
                    b.Navigation("Uydular");
                });

            modelBuilder.Entity("UzayProjectAPI.Models.Uzaylar", b =>
                {
                    b.Navigation("Gezegenler");
                });
#pragma warning restore 612, 618
        }
    }
}
